---
title: "Untitled"
author: "Julia Christensen"
date: "November 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
### Clear global environment
rm(list=ls()) 

### Download Libraries 
# install.packages("pacman")
library(pacman)
p_load(tidyverse, data.table, rmarkdown, knitr, tinytex, magrittr, #basic
       gplots, #for heatmaps
       viridis, RColorBrewer, scales, #good colors
       WDI #world bank data package
       )

### Download data from world bank 
tara_dat <- WDI(country="all", 
                indicator=c("SH.STA.MMRT",
                            "SH.STA.BRTC.ZS",
                            "SP.POP.BRTH.MF",
                            "SP.ADO.TFRT",
                            "SH.DYN.MORT",
                            "SP.DYN.IMRT.IN",
                            "SE.ENR.PRIM.FM.ZS",
                            "SE.ENR.SECO.FM.ZS",
                            "SE.ENR.TERT.FM.ZS",
                            "SH.STA.ANVC.ZS",
                            "SP.M15.2024.FE.ZS",
                            "SH.STA.FGMS.ZS",
                            "SG.DMK.SRCR.FN.ZS",
                            "SG.VAW.ARGU.ZS"),
                start=2000,
                end=2017)

### Take a quick look at downloaded data
glimpse(tara_dat)

### Fix country codes (add 3 letter codes)
cc <- read.csv("country_codes.csv")
tara_dat <- left_join(x=tara_dat, y=cc)

### Clean 
tara_dat %<>%
  # Rename variables (add more)
    rename("mat_mort" = "SH.STA.MMRT",
           "skilled_birth"  = "SH.STA.BRTC.ZS") %>%
  # Filter for 
    filter(!iso3c %in% c("ARB","ARE","CSS","EAP","EAR","EAS","ECA","ECS","EMU",
                         "HIC","HPC","IBD","IBT","IDA","IDB","IDX","INX","LAC",
                         "LDC","LIC","LMC","LMY","LTE","MEA","MNA","MNP","NCL",
                         "OED","OSS","PRE","PSS","PST","SAS","SSA","SSF","SST",
                         "TEA","TEC","TLA","TMN","TSA","TSS","UMC")) 

### Transform data to eyeball it
# tara_dat_short <- tara_dat %>%
#   select(country, year, iso2c, SH.STA.MMRT) %>% #Change variable name at end
#   spread(key=year, value=SH.STA.MMRT) #Change variable name at end

### Set theme  (NOTE: Changed font size)
theme_ed <- theme(
  text = element_text(size=13),
  axis.text.y = element_text(colour="black",size=12),
  axis.text.x = element_text(colour="black",size=12),
  legend.position = "bottom",
  panel.background = element_rect(fill = NA),
  panel.border = element_rect(fill = NA, color = "grey75"),
  axis.ticks = element_line(color = "grey85"),
  panel.grid.major = element_line(color = "grey95", size = 0.2),
  panel.grid.minor = element_line(color = "grey95", size = 0.2),
  legend.key = element_blank())

### Heatmaps 

# Select interesting group of countries 
countries_tara_likes <- c("AFG","BDI","BEN","BFA","BGD",
                          "BOL","BRA","BWA","CAF","CMR",
                          "COD","COL","ERI","ETH","FRA",
                          "GEO","GRC","GTM","IND","IRN",
                          "IRQ","CHM","LBY","LBR","MEX",
                          "MLI","MWI","NER","NGA","NOR",
                          "PAK","PFL","RUS","SDN","SLV",
                          "SOM","SWE","TCD","TUN","USA",
                          "XKX","YEM","IDN")

# Heatmap for interesting group of countries selected above 
tara_dat %>%
  filter(iso3c %in% countries_tara_likes) %>% #filter for select countries
  ggplot(aes(x=year, y=country, fill=mat_mort)) + #CHANGE FILL VARIABLE
    geom_tile(color = NA) +
    scale_fill_viridis(alpha = 1, begin = 0, end = 1, 
                       direction = -1, discrete = FALSE, option = "D", #change scale options
                       name = "Key:") +
    ylab(NULL) + xlab(NULL) + 
    ggtitle(paste0("Maternal Mortality (per 100,000)")) + #change title to match varaible 
    theme_ed +  #thanks ed!
    theme(legend.position = "right", #where legend is located
          text = element_text(size=15), #change general text size 
          axis.text.y = element_text(colour="black",size=8), #change country name size 
          axis.text.x = element_text(colour="black",size=14)) #change year size 


# Heatmap for chuncks of countries (alphabetically ordered)
iso3c_all <- distinct(tara_dat, iso3c)

tara_dat %>%
  filter(iso3c %in% iso3c_all$iso3c[1:25]) %>% #filter for select countries
  ggplot(aes(x=year, y=country, fill=mat_mort)) + #make heatmap 
    geom_tile(color = NA) +
    scale_fill_viridis(alpha = .5, begin = 0, end = 1, 
                       direction = -1, discrete = FALSE, option = "B",
                       name = "Key:") +
    ylab(NULL) + xlab(NULL) +
    ggtitle(paste0("Maternal Mortality (per 100,000)")) +
    theme_ed + 
    theme(legend.position = "right",
          text = element_text(size=15),
          axis.text.y = element_text(colour="black",size=8), #change country name size 
          axis.text.x = element_text(colour="black",size=14)) #change year size 

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
